# Generated by Django 4.2.4 on 2023-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=70)),
                ('sexo', models.CharField(max_length=10)),
                ('fechaIngreso', models.DateField()),
                ('departamento', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
