# Generated by Django 4.2.4 on 2023-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='Sin especificar', max_length=25),
            preserve_default=False,
        ),
    ]
