# Generated by Django 4.2.4 on 2023-12-09 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0003_contactoemergencia_cargafamiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargafamiliar',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_familiares', to='empleados_app.empleado'),
        ),
    ]
