# Generated by Django 4.2.4 on 2023-12-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0005_alter_contactoemergencia_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargafamiliar',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados_app.empleado'),
        ),
    ]
